- README.md
- website/docs_md/getting-started.md
- website/docusaurus.config.js
Thank you for creating a wonderful library. I corrected the minor words while reading the document. Please review together.
https://en.wikipedia.org/wiki/JavaScript
> fix: typo javascript -> JavaScript

- test/isArray.spec.ts
- test/isString.spec.ts
- type-check/isArray.test.ts
- type-check/isString.test.ts
Hi :) I added missing unit tests for `isArray` and `isString` since It's not coved by unit tests. Please review on it. Thanks!
> test: add unit tests

- src/reduce.ts
- test/pipe.spec.ts
- type-check/reduce.test.ts
> fix: missed signature in reduce function

- README.md
To show concurrent situations and error handling
> docs: add concurrent example to README.md

- src/index.ts
- src/join.ts
- test/join.spec.ts
- type-check/join.test.ts
> feat: add `join` function

- src/types/Tail.ts
- type-check/types/Tail.test.ts
Change `Tail` type definition to use `Variadic Tuple Types`
> fix: change tail type definition

- src/Lazy/index.ts
- src/Lazy/split.ts
- test/Lazy/split.spec.ts
- type-check/Lazy/split.test.ts
> feat: add split function 

- src/Lazy/dropUntil.ts
- src/Lazy/index.ts
- test/Lazy/dropUntil.spec.ts
- type-check/Lazy/dropUntil.test.ts
> feat: add dropUntil function 

- src/Lazy/index.ts
- src/Lazy/pluck.ts
- test/Lazy/pluck.spec.ts
- type-check/Lazy/pluck.test.ts
> feat: add `pluck` function

- src/Lazy/index.ts
- src/Lazy/zipWith.ts
- test/Lazy/zipWith.spec.ts
- type-check/Lazy/zipWith.test.ts
Fixes #31
we do not support `curry` in `zipWith` not yet
> feat: add zipWith function

- src/curry.ts
- src/index.ts
- src/types/Curry.ts
- src/types/Prepend.ts
- test/curry.spec.ts
- type-check/curry.test.ts
- type-check/types/Length.test.ts
- type-check/types/Prepend.test.ts
> feat: add `curry` function

- src/index.ts
- src/isNil.ts
- test/isNil.spec.ts
- type-check/isNil.test.ts
> feat: add `isNil` function

- src/findIndex.ts
- src/index.ts
- test/findIndex.spec.ts
- type-check/findIndex.test.ts
> feat: add findIndex function

- src/Lazy/concurrent.ts
- src/index.ts
- src/nth.ts
- test/nth.spec.ts
- type-check/nth.test.ts
> feat: add nth function

- src/includes.ts
- src/index.ts
- test/includes.spec.ts
- type-check/includes.test.ts
> feat: add includes function

- test/Lazy/concurrent.spec.ts
Add test when nested concurrent
> test: nested concurrent

- src/index.ts
- src/isObject.ts
- test/isObject.spec.ts
- type-check/isObject.test.ts
> feat: add 'isObject' function

- src/index.ts
- src/sort.ts
- test/sort.spec.ts
- type-check/sort.test.ts
> feat: add 'sort' function

- src/index.ts
- src/noop.ts
- test/noop.spec.ts
- type-check/noop.test.ts
> feat: add `noop` function

- src/consume.ts
- src/index.ts
- test/consume.spec.ts
- type-check/consume.test.ts
> feat: add `consume` function

- src/apply.ts
- src/index.ts
- test/apply.spec.ts
- type-check/apply.test.ts
> feat: implement `apply` function

- src/index.ts
- src/isEmpty.ts
- test/isEmpty.spec.ts
- type-check/isEmpty.test.ts
> feat: add `isEmpty` function

- src/Lazy/cycle.ts
- src/Lazy/index.ts
- test/Lazy/cycle.spec.ts
- type-check/Lazy/cycle.test.ts
> feat: add `cycle` function

- src/Lazy/difference.ts
- src/Lazy/index.ts
- test/Lazy/difference.spec.ts
- type-check/Lazy/difference.test.ts
> feat: add `difference` function

- src/Lazy/index.ts
- src/Lazy/repeat.ts
- test/Lazy/repeat.spec.ts
- type-check/Lazy/repeat.test.ts
> feat: add `repeat` function

- jest.config.cjs
> test: set jest maxWorkers 1

- src/Lazy/differenceBy.ts
- test/Lazy/difference.spec.ts
In case of a primitive value, up to uniq is applied.
> fix: apply differenceBy uniq

- src/index.ts
- src/max.ts
- src/min.ts
- test/max.spec.ts
- test/min.spec.ts
- type-check/max.test.ts
- type-check/min.test.ts
> feat: add max/min function

- src/index.ts
- src/reverse.ts
- src/sort.ts
- test/reverse.spec.ts
- type-check/reverse.test.ts
> feat: add `reverse` function

- src/add.ts
- src/index.ts
- src/isNumber.ts
- test/add.spec.ts
- test/isNumber.spec.ts
- type-check/add.test.ts
- type-check/isNumber.test.ts
> feat: add `add` function

- src/index.ts
- src/size.ts
- test/size.spec.ts
- type-check/size.test.ts
> feat: add `size` function

- src/add.ts
- src/index.ts
- src/isNumber.ts
- src/sum.ts
- test/add.spec.ts
- test/isNumber.spec.ts
- test/sum.spec.ts
- type-check/add.test.ts
- type-check/isNumber.test.ts
- type-check/sum.test.ts
> feat: add `sum` function

- src/sum.ts
- type-check/sum.test.ts
fix it to occur an error below situation
const res0 = sum([1, 'a']); // error
> fix: handle sum type error

- src/index.ts
- src/juxt.ts
- src/types/HasItem.ts
- test/juxt.spec.ts
- type-check/juxt.test.ts
> Add `juxt` function

- src/Lazy/difference.ts
- src/Lazy/index.ts
- src/Lazy/intersectionBy.ts
- test/Lazy/intersectionBy.spec.ts
- type-check/Lazy/intersectionBy.test.ts
> feat: add `intersectionBy` function

- src/Lazy/index.ts
- src/Lazy/intersection.ts
- test/Lazy/intersection.spec.ts
- type-check/Lazy/intersection.test.ts
> feat: add `intersection` function

- src/pickBy.ts
- src/reduce.ts
- src/sort.ts
- src/toArray.ts
Fixes #
- 문서화 내용을 조금 수정했습니다.   
내용 자체를 수정하진 않았고, 표현을 조금 더 명확히 했습니다 :)
> chore: Clarify documentations

- src/evolve.ts
- src/index.ts
- test/evolve.spec.ts
- type-check/evolve.test.ts
> Add `evolve` function

- src/Lazy/index.ts
- src/Lazy/slice.ts
- test/Lazy/slice.spec.ts
- type-check/Lazy/slice.test.ts
> feat: add `slice` function

- src/Lazy/compress.ts
- src/Lazy/index.ts
- test/Lazy/compress.spec.ts
- type-check/Lazy/compress.test.ts
> feat: add `compress` function

- src/index.ts
- src/sort.ts
- src/sortBy.ts
- test/sort.spec.ts
- test/sortBy.spec.ts
- type-check/sortBy.test.ts
> feat: add `sortBy` function

- src/average.ts
- src/index.ts
- test/average.spec.ts
- type-check/average.test.ts
> feat: add `average` function

- src/Lazy/entries.ts
- src/Lazy/index.ts
- src/Lazy/keys.ts
- src/Lazy/values.ts
- test/Lazy/entries.spec.ts
- test/Lazy/keys.spec.ts
- test/Lazy/values.spec.ts
- type-check/Lazy/entries.test.ts
- type-check/Lazy/keys.test.ts
- type-check/Lazy/values.test.ts
> feat: add `keys`, `values` and `entries` functions

- src/isNumber.ts
- website/function.json
- fix wrong `isNumber` documentation
- fix omitted `isNumber` API in website
> docs: fix `isNumber` documentation

- src/nth.ts
- fix wrong `nth` documentation
> docs: fix `nth` documentation

- src/juxt.ts
> docs: fix `juxt` documentation

- src/types/Curry.ts
- test/curry.spec.ts
- type-check/curry.test.ts
I wrote the details on the #139 
Fixes #139
> fix: fix return type in Curry type

- src/Lazy/dropRight.ts
- src/Lazy/index.ts
- test/Lazy/dropRight.spec.ts
- type-check/Lazy/dropRight.test.ts
- website/function.json
> feat: add `dropRight` function

- src/Lazy/index.ts
- src/Lazy/takeRight.ts
- test/Lazy/takeRight.spec.ts
- type-check/Lazy/takeRight.test.ts
- website/function.json
Hi!
Suggestion with PR. I saw that there's a `dropRight` function but not `takeRight`.
As far as I know, some of the fp libraries (lodash, ramda) has this function, and I think it's good to have one in FxTS as well.
I don't think my codes works 100% perfect, maybe it's better rewrite the whole code by maintainers.
But it would be nice if you could give me any advice, and more it would be appreciated if this PR accepted.
Thanks for reading my codes in advance, sorry for my poor English and coding skill 🙏
I hope this library getting more famous and adopted over the others ❤️
> feat: add `takeRight` function

- src/index.ts
- src/isUndefined.ts
- test/isUndefined.spec.ts
- type-check/isUndefined.test.ts
- website/function.json
> feat: add `isUndefined` function

- src/gt.ts
- src/gte.ts
- src/index.ts
- src/lt.ts
- src/lte.ts
- test/gt.spec.ts
- test/gte.spec.ts
- test/lt.spec.ts
- test/lte.spec.ts
- type-check/gt.test.ts
- type-check/gte.test.ts
- type-check/lt.test.ts
- type-check/lte.test.ts
Fixes #151 
But I'm not sure if this is what you want from the issue.
> feat: lt, gt, lte, gte

- src/Lazy/flat.ts
- src/Lazy/flatMap.ts
- src/types/DeepFlat.ts
> fix: export deep flat type

- src/Lazy/append.ts
- src/Lazy/dropUntil.ts
- src/Lazy/dropWhile.ts
- src/Lazy/filter.ts
- src/Lazy/map.ts
- src/Lazy/prepend.ts
- src/Lazy/takeUntil.ts
- src/Lazy/takeWhile.ts
- src/Lazy/toAsync.ts
- src/_internal/utils.ts
- src/add.ts
- src/countBy.ts
- src/delay.ts
- src/each.ts
- src/groupBy.ts
- src/indexBy.ts
- src/omitBy.ts
- src/partition.ts
- src/pickBy.ts
- src/pipe1.ts
- src/tap.ts
- test/pipe.spec.ts
> feat: support thenable

- src/index.ts
- src/isBoolean.ts
- test/isBoolean.spec.ts
- type-check/isBoolean.test.ts
- website/function.json
> feat: add `isBoolean` function

- website/function.json
> docs: remove overlap word

- src/includes.ts
- type-check/includes.test.ts
> feat: improve type inference for the 'includes' function

- src/sum.ts
- test/sum.spec.ts
- type-check/sum.test.ts
- only supoort number type
- empty array returns zero
Fixes #156
> fix(sum): sum function logic

- src/Lazy/split.ts
> docs: fix split function example

- src/index.ts
- src/memoize.ts
- test/memoize.spec.ts
- type-check/memoize.test.ts
Fixes #195
Provides the memoize function with the same interface as [lodash memoize](https://lodash.com/docs/4.17.15#memoize) that users are familiar with.
> feat: add memoize function

- src/negate.ts
> docs: rewriting negate function comment

- src/types/ReturnPipeType.ts
- type-check/pipe.test.ts
> fix: fix the incorrect return type of the pipe function

- website/docs_md/getting-started.md
> docs: add explanation

- src/join.ts
- test/join.spec.ts
- type-check/join.test.ts
> fix: join when parameter is number

- src/isEmpty.ts
- test/isEmpty.spec.ts
Correctly report empty on Map and Set
> feat: isEmpty should also work for Map and Set

- build/generateExports.ts
> fix: prettier

- src/Lazy/flat.ts
> fix: change from recursion to loop

- src/types/ReturnPipeType.ts
- type-check/pipe.test.ts
> fix: pipe return type

- website/docusaurus.config.js
> docs: copyright link

- src/Lazy/fx.ts
> docs: Fixed typing error on fx doc

- src/Lazy/flat.ts
- src/Lazy/fx.ts
> docs: flat args

- src/Lazy/fx.ts
- src/unicodeToArray.ts
- type-check/Lazy/flat.test.ts
- type-check/pipe.test.ts
> fix: `flat` type in `fx`

- website/docs_md/lazy-evaluation.md
> docs: broken links in lazy evaluation docs

- src/Lazy/fx.ts
- test/Lazy/fx.spec.ts
- type-check/Lazy/fx.test.ts
> feat: expose public iterable properties

- website/docs_md/method-chaining.md
ref
https://github.com/marpple/FxTS/pull/275
> docs: fix Method-Chaining example results

- src/each.ts
- src/head.ts
- src/index.ts
> feat: also can use forEach instead of each

- src/Lazy/fx.ts
> feat: add forEach to `fx`

- website/docusaurus.config.js
> chore: fix prettier

- website/src/pages/index.js
> docs: console.log try to use fx

- src/index.ts
- src/isDate.ts
- test/isDate.spec.ts
- type-check/isDate.test.ts
- website/function.json
- website/markdown-plugin/src/function.json
> feat: Add `isDate` function

- website/console.js
- website/docusaurus.config.js
- website/src/pages/index.js
> feat: add global console.log

- src/Lazy/fx.ts
- src/Lazy/index.ts
- src/Lazy/takeUntil.ts
- src/Lazy/takeUntilInclusive.ts
- src/every.ts
- src/some.ts
- test/Lazy/takeUntilInclusive.spec.ts
- type-check/Lazy/takeUntilInclusive.test.ts
- website/function.json
- website/markdown-plugin/src/function.json
> feat: change `takeUntil` to `takeUntilInclusive`

- src/when.ts
- website/function.json
- website/markdown-plugin/src/function.json
> docs: add `when`

- src/Lazy/fx.ts
- test/Lazy/zip.spec.ts
- type-check/Lazy/zip.test.ts
> feat: add `zip` to `fx`

- src/Lazy/fx.ts
- test/head.spec.ts
- type-check/head.test.ts
> feat: add `head` to `fx`

- src/prop.ts
- test/prop.spec.ts
- type-check/prop.test.ts
Fixes #308 
Please let me know if you have any problems:)
> fix: type inference to work correctly

- website/function.json
- website/markdown-plugin/src/function.json
> docs: add `transpose`

- src/index.ts
Fixes #
Modified the situation where `.js` is attached to the folder in esm
> fix: export path

- src/Lazy/fx.ts
- src/Lazy/index.ts
- src/Lazy/shuffle.ts
- src/index.ts
- src/shuffle.ts
- test/Lazy/shuffle.spec.ts
- test/fx-shuffle.spec.ts
- test/shuffle.spec.ts
- type-check/Lazy/shuffle.test.ts
- type-check/shuffle.test.ts
- Add core shuffle function in `src/shuffle.ts` with Fisher-Yates algorithm
- Add lazy evaluation version in `src/Lazy/shuffle.ts` with iterator support
- Add shuffle method to fx() method chaining (FxIterable/FxAsyncIterable)
- Support for arrays, strings, sync/async iterables, and concurrent processing
- Maintain full TypeScript type inference and FxTS conventions
- **Fisher-Yates algorithm**: Ensures uniform random distribution
- **Multiple formats**: Works with arrays, strings, and iterables
- **Sync/Async support**: Full compatibility with Promise and AsyncIterable
- **Lazy evaluation**: Memory-efficient iterator-based processing
- **Method chaining**: Integrates seamlessly with fx() chains
- **Concurrent processing**: Supports FxTS concurrent operations
- **Type safety**: Complete …
> feat: add shuffle function with Fisher-Yates algorithm
