src/Lazy/compact.ts
src/Lazy/zip.ts
src/countBy.ts
src/head.ts
src/identity.ts
src/partition.ts
src/pipe.ts
src/tap.ts
website/docs_md/getting-started.md
website/docs_md/overview.md

Fixes #
- 문서의 표현을 조금 더 명확하게 수정해 봤습니다. 확인 해 주시면 감사하겠습니다 :)
- 문서 내용 중 truth test 라는 단어가 자주 보이는데, 혹시 predicate로 바꿔보면 어떨까 싶습니다!
- 감사합니다 :)

docs: Fix typos and clarify statements

---

src/Lazy/filter.ts
src/types/Falsy.ts
src/types/TrutyTypesOf.ts
test/Lazy/filter.spec.ts
type-check/Lazy/filter.test.ts

This PR is to make better type inference of filter function when boolean constructor is used.
```ts
const res = filter(Boolean, [undefined, null, 0, "", false, -0, 123] as const) // IterableIterator<123> 
```

feat: add overloading type of 'filter' function

---

README.md
package.json
src/Lazy/filter.ts
src/Lazy/uniqBy.ts
type-check/Lazy/filter.test.ts

To make `type predicate` work as expected in filter function.
I forgot to add this one in previous PR 😄 
```ts
declare function isString(s: unknown): s is string;
const res5 = filter(isString, [1, "a", true]); // IterableIterator<string>
```

feat: add type predicate overloading of 'filter' function

---

src/Lazy/filter.ts
src/Lazy/map.ts
src/Lazy/zip.ts
test/Lazy/append.spec.ts
test/Lazy/chunk.spec.ts
test/Lazy/compact.spec.ts
test/Lazy/concat.spec.ts
test/Lazy/concurrent.spec.ts
test/Lazy/drop.spec.ts
test/Lazy/filter.spec.ts
test/Lazy/flat.spec.ts
test/Lazy/flatMap.spec.ts
test/Lazy/map.spec.ts
test/Lazy/peek.spec.ts
test/Lazy/prepend.spec.ts
test/Lazy/reject.spec.ts
test/Lazy/take.spec.ts
test/Lazy/takeUntil.spec.ts
test/Lazy/takeWhile.spec.ts
test/Lazy/uniq.spec.ts
test/Lazy/uniqBy.spec.ts
test/Lazy/zip.spec.ts
test/Lazy/zipWithIndex.spec.ts
test/utils.ts

pass missing 'concurrent' as parameter to async-iterable's 'next

fix: pass missing 'concurrent' as parameter to async-iterable's 'next

---

src/Lazy/takeUntil.ts
src/Lazy/takeWhile.ts
test/Lazy/takeUntil.spec.ts
test/Lazy/takeWhile.spec.ts

If the requested order is different, the response order must be controlled

fix: concurrent handling takeUntil/takeWhile

---

src/Lazy/dropWhile.ts
src/Lazy/index.ts
test/Lazy/dropWhile.spec.ts
type-check/Lazy/dropWhile.test.ts

feat: add `dropWhile` function 

---

src/Lazy/takeUntil.ts
test/Lazy/takeUntil.spec.ts

we did not test like this
```ts
it("should be able to take the element", async function () {
const fn = jest.fn();
const res = await pipe(
toAsync([3, 3, 1, 0, 0]),
peek(fn),
map((a) => delay(100, a)),
takeUntil((a) => a < 3),
toArray,
);
expect(fn).toHaveBeenCalledTimes(3);
expect(res).toEqual([3, 3, 1]);
}, 350);
```

fix: consume iterable as many as call in takeUntil 

---

test/Lazy/dropUntil.spec.ts
test/Lazy/dropWhile.spec.ts
test/Lazy/filter.spec.ts
test/Lazy/flat.spec.ts

Our tests fail intermittently. https://github.com/marpple/FxTS/pull/39
There are 'timeout' related issues with `jest`, which may not be ours.
https://github.com/facebook/jest/issues?q=is%3Aissue+is%3Aopen+timeout+
If the problem continues, we need to look into it.

Adjust 'timeout' number appropriately

---

src/find.ts

refactor: change find return type

---

src/every.ts
test/every.spec.ts
type-check/every.test.ts

It seems better to follow [mdn every](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)
when array is empry, `every` result is true

fix: every type

---

src/Lazy/peek.ts
src/tap.ts
test/tap.spec.ts
type-check/tap.test.ts

why?
If the auxiliary function of tap is asynchronous, it is more natural to wait and return the original value.

fix: handle tap async

---

jest.config.cjs
package.json

I found tests of FxTs are consist of for type check and for unit test.
But all type check only tests run and are failed when I run `npm test`.
Your test script specified glob pattern of under `/test` directory. But jest does't recognize it.
So, I investigated about it. and I found an issue about this. ([comment](https://github.com/facebook/jest/issues/7108#issuecomment-604905294)). and I referred to the comment and changed your config.
I'm still confused why jest doesn't work with your config. But I guess It's because of micromatch which is used for glob pattern.
BEFORE:
all type check tests are failed
AFTER:
all type check tests are not target.
ps. Sometimes some tests are failed because they depend on timeout api. I think it'd be nice to fix it. thx

fix: change wrong pattern for test

---

website/docs_md/getting-started.md

There is a small typo in website/docs_md/getting-started.md.
Should read `inferred` rather than `inffered`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, inffered -> inferred

---

src/Lazy/differenceBy.ts
src/Lazy/index.ts
test/Lazy/differenceBy.spec.ts
type-check/Lazy/differenceBy.test.ts

Fixes #86 
Unlike `ramda`, we put the item of the second iterable(`iterable2`) as the first function argument.
Also,`ramda` filter by the first iterable, while FxTS filters by the second iterable.
ramda
```ts
const cmp = (x, y) => x.a === y.a;
const l1 = [{a: 1}, {a: 2}, {a: 3}];
const l2 = [{a: 3}, {a: 4}];
R.differenceWith(cmp, l1, l2); //=> [{a: 1}, {a: 2}]
```
FxTS
```ts
const iter = differenceBy(a => a.x, [{ x: 1 }, { x: 4 }], [{ x: 1 },  { x: 2 },  { x: 3 }])
iter.next(); // {value: {x: 2}, done: false}
iter.next(); // {value: {x: 3}, done: false}
iter.next(); // {value: undefined, done: true}
```

feat: add `differenceBy` function

---

src/Lazy/index.ts
src/Lazy/scan.ts
test/Lazy/scan.spec.ts
type-check/Lazy/scan.test.ts

feat: add `scan` function

---

src/Lazy/cycle.ts
src/Lazy/drop.ts
src/Lazy/dropUntil.ts
src/Lazy/dropWhile.ts
src/Lazy/filter.ts
src/Lazy/flatMap.ts
src/Lazy/map.ts
src/Lazy/peek.ts
src/Lazy/reject.ts
src/Lazy/split.ts
src/Lazy/take.ts
src/_internal/utils.ts
src/average.ts
src/countBy.ts
src/each.ts
src/every.ts
src/find.ts
src/groupBy.ts
src/indexBy.ts
src/join.ts
src/max.ts
src/min.ts
src/nth.ts
src/partition.ts
src/some.ts

very minor change 
change return type of `isIterable` util function for better type inference.

fix: change return type of `isIterable`

---

src/tap.ts
test/tap.spec.ts

It should support asynchronous function when `tap` is curried

fix: support async tap when curried

---

src/average.ts
src/max.ts
src/min.ts

- `max` , `min` : fix example result
- `average` : add empty array example
😄

docs: `max` , `min` , `average`

---

src/Lazy/entries.ts
src/fromEntries.ts
src/index.ts
test/fromEntries.spec.ts
type-check/fromEntries.test.ts
website/function.json

Hi all,
I wrote a `fromEntries` function that performs inverse of `entries` function(key-value pair iterable/asyncIterable to an object).
This function supports type inference well.
My English is not very good, so there may be some strange English descriptions.
And also, maybe my test cases are weird or poorly written.
Any advice would be welcome. 😄

feat: add `fromEntries` function

---

src/Lazy/flat.ts
src/Lazy/flatMap.ts
src/types/DeepFlat.ts
type-check/Lazy/flat.test.ts
type-check/Lazy/flatMap.test.ts

fix: fix incorrect type inference of flat and flatMap functions

---

src/average.ts

Thank you for providing a good library.
There was a difference between the test code and the actual annotation, so I fixed it.
[average docs](https://fxts.dev/docs/average)
```tsx
// average.spec.ts
it.each([
[[1, 2, 3, 4, 5], 3],
[[], NaN],
])(
"should return the average of the given elements",
function (nums, result) {
expect(average(nums)).toEqual(result);
},
);
it("should be able to be used as a curried function in the pipeline", function () {
const res = pipe([1, 2, 3, 4, 5], average);
expect(res).toEqual(3);
});
```
Thank you😎

fix: comment result of `average()` function

---

src/partition.ts
type-check/partition.test.ts

Fixes #181 
Improved type inference of `partition` function when receiving custom typeguard function as an argument.
```ts
const res = partition(
(a): a is number => typeof a === "number",
[1, 2, "a", "b", true, false],
);
// As-is
// typeof res == [(number | string | boolean)[], (number | string | boolean)[]]
// To-be
// typeof res == [number[], (string | boolean)[]]
```

feat: improved type inference of `partition` function

---

src/Lazy/concurrent.ts

Concurrent allows undefined values for its length parameter. It was my mistake, but it caused Node to consume all CPU resources. Moreover, it didn't throw any errors, which wasted time trying to find the cause of the issue. Therefore, I strongly believe that this issue must be fixed.
Fixes #

Fix: length must not be undefined

---

src/memoize.ts

Fixes #195 
If the return type of the resolver function is object, then the cache should be assigned to a `WeakMap`. Currently only `Map` is used.

fix: modify to use WeakMap properly in cache of memoize

---

src/groupBy.ts
src/indexBy.ts
src/types/Equals.ts
src/types/ExcludeObject.ts
src/types/GetKeyOf.ts
src/types/ReturnPartitionType.ts
type-check/groupBy.test.ts
type-check/indexBy.test.ts

Fixes #197 
This change is a fix for the following issue: https://github.com/marpple/FxTS/pull/199#discussion_r1161289493
```ts
type Data = { id: number; state1: 'created' | 'deleted', state2: 'created' | 'deleted' };
const list: Data[] = [...];
const res = groupBy(a => a.state1, list);
// typeof res
// AS-IS: { created: { id: number; state1: 'created', state2: 'created'}[]; deleted: { id: number; state1: 'deleted', state2: 'deleted'}[]  }
// TO-BE: { created: Data[]; deleted: Data[] }
```

fix: improve type inference for groupBy and indexBy functions

---

src/isEmpty.ts

if value is object, it have to literal object and have no method and property.
if value is instance of class, isEmpty always return true. ex) Date, Custom Class, .....
- but array instance is considered to have item or not.

refactor: change isEmpty logic

---

src/isArray.ts
src/isBoolean.ts
src/isEmpty.ts
src/isNil.ts
src/isNull.ts
src/isNumber.ts
src/isObject.ts
src/isString.ts
src/isUndefined.ts
src/last.ts
src/sort.ts
src/sortBy.ts
type-check/isArray.test.ts
type-check/isBoolean.test.ts
type-check/isNil.test.ts
type-check/isNull.test.ts
type-check/isNumber.test.ts
type-check/isObject.test.ts
type-check/isString.test.ts
type-check/isUndefined.test.ts

pipe안에서 성공/실패 케이스 모두에 대해 더 정확한 타입 결과를 나타낼 것입니다.

refactor: enhance typeguard function type

---

src/sortBy.ts

The `SortBy` is completely same `Sort`. Therefore, remove duplicate and using internal implementation.

fix(sort): replace with internal sort

---

src/Lazy/entries.ts
type-check/Lazy/entries.test.ts

feat: enhance entries type

---

src/every.ts
src/join.ts
src/reduce.ts
src/some.ts
test/reduce.spec.ts
type-check/reduce.test.ts

feat: change `reduce` behavior, when empty iterable

---

src/reduce.ts

At first I mentioned`R` but more describing `Acc` would be better.
- Change type `A`,`B` into `T`, `Acc` for `reduce`
- Give proper value name for `acc`, `value` instead of `a`, `b`
- Add example with explicit seed
- Add `@typeParam` for [tsdoc](https://tsdoc.org/pages/tags/typeparam/) support
Fixes #240

fix(reduce): better type and docs for `reduce` (#240)

---

src/Lazy/index.ts
src/Lazy/reduceLazy.ts
src/reduce.ts
src/types/Reducer.ts
test/Lazy/reduceLazy.spec.ts
type-check/Lazy/reduceLazy.test.ts

Fixes #239 
- Extract type of function argument in `reduce` as `SyncReducer` and `AsyncReducer`
- This is because they are both used in `reduce` and `reduceLazy`
- It's more concise than messy raw arrowy type
- Implement `reduceLazy`
- At first I thought the implementation of `reduce` covers lazy cases 100%, but it wasn't
- To resolve issue just relay `reduce` with rich dedicated types
- Add type test and spec test for `reduceLazy`
- Type tests were desigend using exhaustive cartessian thinking of following three dimension:
- *homogeneous* vs *heterogeneous*
- `SyncReducer` vs `AsyncReducer`
- `Iterable` vs `AsyncIterable`
- Spec tests were almost identical to `reduce`
- Test for promise rejection was omitted since it is responsible for `reduce`

feat: implement `reduceLazy` (#239)

---

src/Lazy/index.ts
src/Lazy/reduceLazy.ts
src/reduce.ts
src/types/Reducer.ts
test/Lazy/reduceLazy.spec.ts
type-check/Lazy/reduceLazy.test.ts

feat: add reduceLazy

---

jest.config.cjs
test/Lazy/append.spec.ts
test/Lazy/chunk.spec.ts
test/Lazy/concat.spec.ts
test/Lazy/concurrent.spec.ts
test/Lazy/cycle.spec.ts
test/Lazy/difference.spec.ts
test/Lazy/drop.spec.ts
test/Lazy/dropRight.spec.ts
test/Lazy/dropUntil.spec.ts
test/Lazy/dropWhile.spec.ts
test/Lazy/filter.spec.ts
test/Lazy/flat.spec.ts
test/Lazy/intersection.spec.ts
test/Lazy/prepend.spec.ts
test/Lazy/reverse.spec.ts
test/Lazy/scan.spec.ts
test/Lazy/split.spec.ts
test/Lazy/takeRight.spec.ts
test/Lazy/zip.spec.ts
test/tap.spec.ts
test/utils.ts

In the concurrent test, we test for the maximum time and
We also tested the minimum time,
The setTimeout behavior for minimum time tests intermittently does not work as we intended. This seems to be related to the fact that the setTimeout callback does not work immediately at the originally specified time.
Testing for maximum time is important, so avoid testing for minimum time.

test: exclude non-deterministic tests for `setTimeout`

---

README.md
src/Lazy/fx.ts
src/Lazy/index.ts
test/Lazy/append.spec.ts
test/Lazy/concurrent.spec.ts
test/Lazy/drop.spec.ts
test/Lazy/filter.spec.ts
test/Lazy/flat.spec.ts
test/Lazy/flatMap.spec.ts
test/Lazy/fx.spec.ts
test/Lazy/map.spec.ts
test/Lazy/peek.spec.ts
test/Lazy/slice.spec.ts
test/Lazy/take.spec.ts
test/Lazy/takeUntil.spec.ts
test/Lazy/takeWhile.spec.ts
test/each.spec.ts
test/every.spec.ts
test/find.spec.ts
test/findIndex.spec.ts
test/groupBy.spec.ts
test/indexBy.spec.ts
test/join.spec.ts
test/reduce.spec.ts
test/some.spec.ts
type-check/Lazy/fx.test.ts
website/docs_md/method-chaining.md
website/function.json
website/sidebars.js
website/tsdoc-metadata.json

Fixes #250 
Supports method chaining only for commonly used functions.

feat: add `fx`

---

src/unless.ts

I found it while building doc.
```
Reading website.api.json
MarkdownFeature: onInitialized()
Deleting old output from docs
Writing website package
Unsupported block tag: @return <--
MarkdownFeature: onFinished
```
`return` is invalid tag. Replace to `returns`.

fix(unless): invalid return tag

---

src/Lazy/dropUntil.ts

```ts
// The example answer is 3, 4, 5, but the correct answer is 2, 3, 4, 5, 1, 2 
const iter = dropUntil((a) => a < 3, [1, 2, 3, 4, 5, 1, 2])
```
I think it is a mistake copying and pasting `dropWhile`. Considering the context, I think it's the right way to change it as follows.
```ts
const iter = dropUntil((a) => a > 3, [1, 2, 3, 4, 5, 1, 2]);
```

fix: dropUntil.ts example

---

src/Lazy/uniq.ts
src/Lazy/uniqBy.ts

refactor: update uniq and uniqBy function docs

---

src/sort.ts

docs: example sort

---

src/Lazy/differenceBy.ts
src/Lazy/flatMap.ts
src/Lazy/intersectionBy.ts
src/Lazy/map.ts
src/Lazy/zipWith.ts
src/_internal/error.ts
src/every.ts
src/some.ts
test/Lazy/map.spec.ts
type-check/Lazy/map.test.ts

feat: `map`function supports Iterable<Promise<T>>

---

src/Lazy/fx.ts
test/Lazy/fx.spec.ts

feat: add `to` to `fx`

---

src/Lazy/dropRight.ts
src/Lazy/takeRight.ts
src/isArray.ts
src/isBoolean.ts
src/isNil.ts
src/isNull.ts
src/isNumber.ts
src/isObject.ts
src/isString.ts
src/isUndefined.ts
src/types/FalsyTypeOf.ts
src/types/Include.ts
type-check/throwError.test.ts

Fixes #
기존 타입가드 함수의 타입 추론 결과의 정확도를 향상시켰습니다.
최신 TS 버전은 타입가드의 결과를 input 타입과 교집합으로 계삽합니다. 이를 참고하여 타입 연산식을 수정했습니다.
아쉽게도 여전히 input이 any인 경우는 잘못된 결과가 추론됩니다.
before
```ts
isString(input: any); // input is any;
isString(input: unknown); // input is never;
isString(input: number | "1" | "2"); // input is "1" | "2";
```
after
```ts
isString(input: any); // input is any;
isString(input: unknown); // input is string;
isString(input: number | "1" | "2"); // input is "1" | "2";
isString(input: number); // input is never;
```

refactor: typeguard 타입추론 개선

---

.github/CODEOWNERS
src/Lazy/fx.ts
test/Lazy/chunk.spec.ts
type-check/Lazy/chunk.test.ts

feat: add `chunk` to `fx`

---

website/docusaurus.config.js

Fix incorrect active color in navigation bar
Previously, the navigation items in both doc and API sections were highlighted simultaneously.
This PR separates the active states by.
- Using `docId` to determine which item should be highlighted
This ensures only the correct navigation item is highlighted at a time.
https://github.com/user-attachments/assets/25c682c3-0fec-4bdd-a8de-57b5fb1d0072

fix: fix incorrect active color in navigation bar

---

build/generateExports.ts

Fixes #294 
as-is (package.json)
to-be

fix: add filter to remove falsy values in generateExports

---

src/Lazy/fx.ts
src/Lazy/index.ts
src/Lazy/map.ts
src/head.ts
src/includes.ts

feat: support mapEffect

---

src/Lazy/concurrentPool.ts
src/Lazy/index.ts
test/Lazy/concurrent.spec.ts
test/Lazy/concurrentPool.spec.ts
type-check/Lazy/concurrentPool.test.ts
website/function.json
website/markdown-plugin/src/function.json

Fixes #304
I'd like to get feedback from you  @ysm-dev 
What do you think about the expression and behavior?

feat: add `concurrentPool`

---

src/Lazy/fx.ts
test/Lazy/zip.spec.ts
type-check/Lazy/zip.test.ts

Fixes the order in which zip evaluates arguments is reversed.

fix: change `fx.zip` evaluation arguments  order

---

src/Lazy/fx.ts
type-check/Lazy/fx.test.ts

Fixes #
I encountered some inconvenience when using the filter method on the fx object.
It seems that when using a type guard function with filter, it doesn't affect the resulting type as expected.
To address this, I added an overload to the filter method on the fx object.
I’d appreciate it if you could take a look. 🙇‍♂️
before: 
after:

fix: add filter overload to fx

---

src/Lazy/entries.ts
type-check/Lazy/entries.test.ts

A situation where the type does not work based on the JavaScript runtime behavior.
Modified to transfer types based on the JavaScript runtime behavior.
Both string and number are entered as key values ​​in the object.
```
var obj = { 2025 : 'hello' }
obj[2025] // hello
obj['2025'] // hello
```
The results of `Object.keys(obj)`, `Object.entries`, and `for k in obj` are all strings, so if the first key of `entries` is a number, the type is transferred as string.
The existing response type is maintained(Maintaining backward compatibility)

fix: entries return type

---

src/isArray.ts
type-check/isArray.test.ts

Fixes #317 
**This changes that use `Extract` utility type instead of instersection type prevent unintented type widening.**
In the previous implemetation generic type `T` has been sometimes interpreted as `unknown[]` because of tendency to widen types.
**All tests were passed.**

fix: use Extract type for preventing type widening in isArray function

---

type-check/isArray.test.ts
website/README.md
website/function.json
website/markdown-plugin/package-lock.json
website/markdown-plugin/package.json
website/markdown-plugin/src/MarkdownFeature.ts
website/markdown-plugin/src/Signature.ts
website/markdown-plugin/src/function.json
website/tsdoc-metadata.json

Fixes #326
- api-extractor is no longer supported, so upgrade the version
- add `debounce`

docs: `add` debounce

---

src/Lazy/concurrentPool.ts

expected 900 ms. not 2 sec.
Fixes #

docs: edit example concurrentPool

---

src/when.ts
test/when.spec.ts
type-check/when.test.ts

**This PR enhances the `when` utility by correcting its return type signature** when used with a type guard predicate, significantly improving its type safety and predictability.
**This issue stems from a fundamental aspect of TypeScript's design: type checking occurs at compile-time without executing the code.** The type system cannot predict the runtime outcome of the predicate function (whether it will return `true` or `false`). **Therefore, a function's type signature must correctly account for all possible return paths.**
The previous signature for when with a type guard `((input: T) => input is S)` incorrectly returned `Exclude<T, S>`. This signature only described the outcome for a `false` predicate, creating a serious mismatch when the predicate was `true` at runtime.
For example, …

fix: Improve `when` function's type safety for type guard predicates

---

src/groupBy.ts

I will fix the code that was not cleaned up in #339.
I will clean up the import statements in groupBy, removing any duplicate imports and also eliminating variables that are imported but not used.

refactor: groupBy import variables
